[project]
name = "parseelectrdata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "psutil>=7.0.0",
    "pyinstaller>=6.12.0",
    "sv-ttk>=2.6.0",
]
